project:
  type: website
  output-dir: docs

execute:
  echo: true

book:
  title: "Title of your project"
  author: "Your Name"
  chapters:
    - index.qmd
    - part: "Reports"
      chapters: 
      - reports/manuscript.qmd
      - reports/supplementary.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/01_notebook.ipynb
      - notebooks/02_notebook.ipynb
    - part: "Howtos"
      chapters: 
      - howtos/genomedk.qmd
      - howtos/reproducible.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-width: 5
    fig-height: 3
  pdf:
    documentclass: scrbook
    fig-width: 7
    fig-height: 5
    toc-depth: 2

