project:
  type: book
  # output-dir: docs

execute:
  echo: true

book:
  title: "Title of your project"
  author: "Your Name"
  chapters:
    - index.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/01_notebook.ipynb
      - notebooks/02_notebook.ipynb
      - notebooks/jupyter_walk_through.ipynb
    - part: "Reports"
      chapters: 
      - reports/manuscript.qmd
      - reports/supplementary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 2

