project:
  type: book
  # output-dir: docs
  post-render: 
    - bash slides.sh  

execute:
  freeze: auto
  echo: true

book:
  title: "Title of your project"
  author: "Your Name"
  chapters:
    - index.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/01_weather.ipynb
      - notebooks/02_interaction.ipynb
    - part: "Reports"
      chapters: 
      - reports/manuscript.ipynb
      - reports/supplementary.qmd
    - part: "Slides"
      chapters:
       - slides/slides.qmd 
       - slides/suppl_slides.qmd
       # the same slide files must also be listed in slides/_quarto.yml
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

