# Project {.unnumbered}

These pages are generated from a the content of a termplate Git repository, I made for you. You can read more about Git and repositories in the [project guide](https://munch-lab.github.io/project-guide). This repository serves both as an initial scaffold for your project, with placeholder files to get you started, and as a means of documenting and reporting your work. During the project, you will populate with your own texts, code, analysis notebooks, and documentation. 

## Outline

Here you should write a paragraph outlining the project to the extent you can at this point. What are the goals of your project? What would you like to find out? What would you like to learn? You should update it along the way.

## Suggested reading

If you need a basic introduction to population genetics, I suggest reading "An introduction to population genetics: Theory and applications" by Rasmus Nielsen and Monty Slatkin [@NielsenSlatkin2016]. A free alternative is [Graham Coop's Lecture notes](https://github.com/cooplab/popgen-notes), which offer a similar introduction.

<!-- 
These are additional some suggestions for background reading:

- [Genetic Villains: Killer Meiotic Drivers](https://doi.org/10.1016/j.tig.2018.02.003), is a review on meiotic drive.
- [Extraordinary selection on the human X chromosome associated with archaic admixture](10.1016/j.xgen.2023.100274) is our most recent paper on the topic.
- -->

I will guide you to additional material once you get started.

## Schedule

Once you get started and you should make an plan for your project. It will change along the way, but with a plan, you will know when it does. 

Here you should outline project plan and what you intend to do in the weeks/months of your project. This is ofcause tentative and will change along the way. But it is important that it changes because you decide it is meaningful.

A good way to do this is to use [GitHubs Project feature](https://github.com/orgs/munch-lab/projects) on our the group GitHub account.

